apiVersion: v1
kind: Plugin
metadata:
  author: langbot-app
  name: langbot-plugin-rag
  repository: ''
  version: 0.1.0
  description:
    en_US: 'langbot-plugin-rag'
    zh_Hans: 'langbot-plugin-rag'
  label:
    en_US: langbot plugin rag
    zh_Hans: langbot plugin rag
  icon: assets/icon.svg  # replace in assets/icon.svg
spec:
  config: []
  components:
    rag_engine:
      name:
        en_US: Official RAG Engine
        zh_Hans: 官方RAG引擎
      path: components.rag_engine.LangRAG
execution:
  python:
    path: main.py
    attr: langbotpluginrag