apiVersion: v1
kind: RAGEngine
metadata:
  name: langrag
  label:
    en_US: LangRAG
    zh_Hans: LangRAG
  description:
    en_US: Official LangBot RAG Engine with document chunking and vector retrieval
    zh_Hans: 官方 LangBot RAG 引擎，支持文档分块和向量检索
spec: {}
  # creation_schema and retrieval_schema are provided dynamically
  # by LangRAG.get_creation_settings_schema() and get_retrieval_settings_schema()
execution:
  python:
    path: langrag.py
    attr: LangRAG
